---
- name: Create Terraform manifests and components
  hosts: all
  collections:
   - cloud.terraform

  vars:
    instruqt_tf_build: "Ansible_Build"
    working_dir: /tmp/srv/
    
  tasks:
    - name: Create Terraform project 
      ansible.builtin.file:
        path: /{{ working_dir }}/{{ instruqt_tf_build }}
        state: directory
        mode: '755'

    - name: Copy files to locally
      copy: 
        
     
        
- name: Create Terraform manifests and components
  hosts: localhost
  connection: local
  collections:
   - cloud.terraform

  vars:
    instruqt_tf_build: "Ansible_Build"
    working_dir: /tmp/srv/
    
  tasks:
     - name: Clone Terraform Manifests and build repo
       ansible.builtin.git:
        repo: "https://github.com/yathriajkr/terraform_builds.git"
        dest: /tmp/srv
        clone: yes
        
     - name: Clone Terraform Manifests and build repo
       ansible.builtin.git:
        repo: "https://github.com/yathriajkr/terraform_deploy.git"
        dest: "/tmp/srv/src_code"
        clone: yes
                 
     - name: Create Terraform project 
       ansible.builtin.file:
        path: /{{ working_dir }}/{{ instruqt_tf_build }}
        state: directory
        mode: '755'
     

            
     # - name: Create cloud-init for Terraform manifest
     #   ansible.builtin.copy:
     #    src: cloud-init.conf
     #    dest: /{{ working_dir }}/{{ instruqt_tf_build }}/cloud-init.conf
        
     - name: Create main Terraform manifest
       ansible.builtin.copy:
        src: "/tmp/srv/src_code/main.tf"
        dest: /{{ working_dir }}/{{ instruqt_tf_build }}/main.tf
        
     - name: Print data
       command: " ls /{{ working_dir }}/{{ instruqt_tf_build }}"
       register: ls_data
       



