---
- name: Create Terraform manifests and components
  hosts: all
  collections:
   - cloud.terraform

  vars:
    instruqt_tf_build: "Ansible_Build"
    working_dir: /tmp/srv/
    
  tasks:
    - name: Create Terraform project 
      ansible.builtin.file:
        path: /{{ working_dir }}/{{ instruqt_tf_build }}
        state: directory
        mode: '755'
        
    - name: Command
      command:
        ls /tmp/srv
      register: output
      
    - name: Command
      command:
        ls /tmp/srv/
      register: output
        
  



